# Generated by Django 4.1.1 on 2022-10-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tag_profile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
