# Generated by Django 4.1.1 on 2022-10-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
        ('projects', '0002_alter_blog_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Project',
        ),
    ]
