# Generated by Django 4.1.1 on 2022-10-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/caveman.jpeg', null=True, upload_to='images/profiles'),
        ),
    ]
